### ISSUE TITLE
[Feature Request] Collapse a sub tree.

### ISSUE THREAD

**Issue by oychao** [wuyuedefeng/vue-sortable-tree#11]
How do I collapse a sub tree?
I checked the source code and it seems there is no such feature now.

**Comment by wuyuedefeng** [comment]
use `closeStateKey`
demo code: `https://github.com/wuyuedefeng/vue-sortable-tree/blob/master/example/src/components/Hello.vue`

**Comment by oychao** [comment]
@wuyuedefeng That's what I need, thanks.
