### ISSUE TITLE
Demo doesn't work.

### ISSUE THREAD

**Issue by gluons** [wuyuedefeng/vue-sortable-tree#3]
Can't drag anything.

![2017-07-05_09-41-59](https://user-images.githubusercontent.com/4688092/27847156-4e97df20-6166-11e7-860a-fc222af13261.gif)

**My browser:** Firefox Developer 55 on Windows 10.

**Comment by wuyuedefeng** [comment]
Ok, I has fixed at v1.0.20, you can try again!

**Comment by gluons** [comment]
OK. I'll try it.

**Comment by gluons** [comment]
@wuyuedefeng Seems that Firefox will redirect to `http://null` after drop an item.

![2017-07-06_10-00-50](https://user-images.githubusercontent.com/4688092/27893792-250e0360-6232-11e7-8046-38d25037c64a.gif)

**Comment by gluons** [comment]
I've tried it on [my repo](https://github.com/gluons/sortable-tree-test). It doesn't work correctly too.

![2017-07-06_10-03-23](https://user-images.githubusercontent.com/4688092/27893859-9dd0a1c2-6232-11e7-873a-b80873f167ba.gif)

**Comment by wuyuedefeng** [comment]
thank you , is a problem ,  When drop I forget preventDefault, I had try fixed!   v1.0.25, you can try again!

**Comment by gluons** [comment]
Nice! It works fine! Thank you.

Issue fixed 🎉 

<br>

> I'll delete [my sample repo](https://github.com/gluons/sortable-tree-test) after few days.
